### ISSUE TITLE
No Jobs in Workspace Causes Error

### ISSUE THREAD

**Issue by AndrewGuard** [PATRIC3/patric3_website#1490]
Running locally with the production flag set to false, when the user has no jobs in the workspace, the following error is seen in the console:

/js/dojo/promise/instrumentation.js:20 TypeError: Cannot read property 'id' of undefined
    at TMP.getIdentity (/js/dojo/store/Memory.js:56:16)
    at TMP.store.(anonymous function) [as put] (/js/dojo/store/Observable.js:155:25)
    at eval (/js/p3/JobManager.js:25:17)
    at notify (/js/dojo/_base/Deferred.js:187:23)
    at complete (/js/dojo/_base/Deferred.js:168:4)
    at dojo.Deferred.resolve.callback (/js/dojo/_base/Deferred.js:248:4)
    at defer.when.message (/js/p3/jsonrpc.js:26:10)
    at signalListener (/js/dojo/Deferred.js:37:21)
    at signalWaiting (/js/dojo/Deferred.js:28:4)
    at Deferred.resolve (/js/dojo/Deferred.js:192:5) "TypeError: Cannot read property 'id' of undefined
    at TMP.getIdentity (/js/dojo/store/Memory.js:56:16)
    at TMP.store.(anonymous function) [as put] (/js/dojo/store/Observable.js:155:25)
    at eval (/js/p3/JobManager.js:25:17)
    at notify (/js/dojo/_base/Deferred.js:187:23)
    at complete (/js/dojo/_base/Deferred.js:168:4)
    at dojo.Deferred.resolve.callback (/js/dojo/_base/Deferred.js:248:4)
    at defer.when.message (/js/p3/jsonrpc.js:26:10)
    at signalListener (/js/dojo/Deferred.js:37:21)
    at signalWaiting (/js/dojo/Deferred.js:28:4)
    at Deferred.resolve (/js/dojo/Deferred.js:192:5)

**Comment by hyoo** [comment]
i tried new new user account and worked well. i guess we resolved this issue when we revamped the workspace.
