### ISSUE TITLE
ARAST job crashes

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1732]
(See end with note about rogue job. Perhaps that is the real problem here. What is a rogue job and why did this turn rogue?)

We have seen a rash of job failures that manifest in the PATRIC logs as

```
2017-09-24 20:43:39: job 248 status: Queued
2017-09-24 20:54:09: job 248 status: Queued
2017-09-24 21:04:16: job 248 status: Queued
2017-09-24 21:14:44: job 248 status: Queued
2017-09-24 21:25:22: job 248 status: Queued
2017-09-24 21:36:22: job 248 status: Queued
HTTP error: Internal Server Error (HTTP status code 500)

Error running status command ar-stat -j 248: No such file or directory at /disks/p3/deployment/plbin/App-GenomeAssembly.pl line 115.
```

The above were for user lkbryan. Below the ar_server.log around the time job e68909de-54c1-488f-8dbd-574334cd64db failed. 

```
[2017-09-24 21:43:37,280 INFO cherrypy.access.140367007689040] 192.5.200.105 - - [24/Sep/2017:21:43:37] "GET /u
ser/ejuscamaytal@patricbrc.org/job/210/status HTTP/1.0" 200 6 "" "python-requests/2.7.0 CPython/2.7.9 Linux/2.6
.32-642.15.1.el6.x86_64"
[2017-09-24 21:43:37,306 INFO cherrypy.access.140367007689040] 192.5.200.63 - - [24/Sep/2017:21:43:37] "GET /us
er/lkbryan@patricbrc.org/job/258/status HTTP/1.0" 200 6 "" "python-requests/2.7.0 CPython/2.7.9 Linux/2.6.32-64
2.15.1.el6.x86_64"
[2017-09-24 21:43:37,319 INFO cherrypy.access.140367007689040] 192.5.200.105 - - [24/Sep/2017:21:43:37] "GET /u
ser/lkbryan@patricbrc.org/job/252/status HTTP/1.0" 200 6 "" "python-requests/2.7.0 CPython/2.7.9 Linux/2.6.32-6
42.15.1.el6.x86_64"
[2017-09-24 22:01:37,291 ERROR cherrypy.error] [24/Sep/2017:22:01:37]  Traceback (most recent call last):
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 180, in trap
    return func(*args, **kwargs)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 99, in __call__
    return self.nextapp(environ, start_response)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 410, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 234, in __init__
    self.run()
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 349, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError

[2017-09-24 21:43:37,327 INFO cherrypy.access.140367007689040] 192.5.200.63 - - [24/Sep/2017:21:43:37] "GET /us
er/lkbryan@patricbrc.org/job/248/status HTTP/1.0" 200 6 "" "python-requests/2.7.0 CPython/2.7.9 Linux/2.6.32-64
2.15.1.el6.x86_64"
[2017-09-24 22:01:37,293 INFO router] Running: 5a7c300c-4efd-495d-b85a-b27877c85dff
[2017-09-24 21:43:37,331 INFO cherrypy.access.140367007689040] 192.5.200.105 - - [24/Sep/2017:21:43:37] "GET /u
ser/lkbryan@patricbrc.org/job/240/status HTTP/1.0" 200 6 "" "python-requests/2.7.0 CPython/2.7.9 Linux/2.6.32-6
42.15.1.el6.x86_64"
[2017-09-24 21:43:37,348 INFO cherrypy.access.140367007689040] 192.5.200.63 - - [24/Sep/2017:21:43:37] "GET /us
er/lkbryan@patricbrc.org/job/239/status HTTP/1.0" 200 6 "" "python-requests/2.7.0 CPython/2.7.9 Linux/2.6.32-64
2.15.1.el6.x86_64"
[2017-09-24 22:01:37,295 ERROR cherrypy.error] [24/Sep/2017:22:01:37]  Traceback (most recent call last):
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 180, in trap
    return func(*args, **kwargs)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 99, in __call__
    return self.nextapp(environ, start_response)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 410, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 234, in __init__
    self.run()
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 349, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError

[2017-09-24 22:01:37,296 ERROR cherrypy.error] [24/Sep/2017:22:01:37]  Traceback (most recent call last):
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 180, in trap
    return func(*args, **kwargs)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 99, in __call__
    return self.nextapp(environ, start_response)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 410, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 234, in __init__
    self.run()
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 349, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/disks/patric-common/runtime/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError
```

Here is the log around when 262 was submitted

```
[2017-09-24 22:56:07,007 INFO router] Sent to queue: 'jobs.regular': '{"pipeline": null, "job_id": 262, "assemb
ly_data": {"file_sets": [{"tags": [], "read_orientation_outward": "false", "platform": "infer", "file_infos": [
{"shock_url": "http://p3.theseed.org/services/shock_api", "keep_name": false, "local_file": "/scratch/tmp/pfVr2
4cERh/L-09_S1_L001_R1_001.fastq", "shock_id": "8fbfb787-c9a1-426c-8541-f97331a8879a", "filename": "L-09_S1_L001
_R1_001.fastq", "create_time": "2017-09-25 03:48:06.334130", "filesize": 116571762, "direct_url": null, "metada
ta": null}, {"shock_url": "http://p3.theseed.org/services/shock_api", "keep_name": false, "local_file": "/scrat
ch/tmp/pfVr24cERh/L-09_S1_L001_R2_001.fastq", "shock_id": "e88d7149-d837-4100-90cc-1ae9c04553b6", "filename": "
L-09_S1_L001_R2_001.fastq", "create_time": "2017-09-25 03:55:43.662699", "filesize": 91190508, "direct_url": nu
ll, "metadata": null}], "type": "paired", "interleaved": "false"}]}, "data_id": 262, "ARASTUSER": "lkbryan_patr
icbrc_org", "wasp": null, "recipe": ["miseq"], "queue": null, "client": "CLI", "oauth_token": "un=lkbryan@patri
cbrc.org|[elided]", "version": "0.6.0", "message": null, "_id": "76be1bb5-2135-4678-9e69-3ed5d7845c82"}'
[2017-09-24 22:56:07,007 INFO pika.adapters.blocking_connection] Closing connection (200): Normal shutdown
[2017-09-24 22:56:07,010 INFO cherrypy.access.140367007689040] 192.5.200.63 - - [24/Sep/2017:22:56:07] "POST /u
ser/lkbryan@patricbrc.org/job/new HTTP/1.0" 200 3 "" "python-requests/2.7.0 CPython/2.7.9 Linux/2.6.32-642.15.1
.el6.x86_64"
```

Later:

```
[2017-09-24 22:58:37,291 WARNING router] Removing rogue job: 76be1bb5-2135-4678-9e69-3ed5d7845c82
```

Why was this marked a rogue job?

**Comment by olsonanl** [comment]
Inside the ARAST mongo this job is listed as queued:

```
{
  "ARASTUSER": "lkbryan_patricbrc_org",
  "_id": "abf4a5be-e400-4596-a936-f77d5a213baf",
  "assembly_data": {
    "file_sets": [
      {
        "tags": [

        ],
        "read_orientation_outward": "false",
        "platform": "infer",
        "file_infos": [
          {
            "shock_url": "http://p3.theseed.org/services/shock_api",
            "keep_name": false,
            "local_file": "/scratch/tmp/7_Y5klbiK8/38-74_S95_L001_R1_001.fastq",
            "shock_id": "4f873cf9-75a1-4d2a-a651-fa1fab5bf8fd",
            "filename": "38-74_S95_L001_R1_001.fastq",
            "create_time": "2017-09-24 17:50:02.915620",
            "filesize": 225180131,
            "direct_url": null,
            "metadata": null
          },
          {
            "shock_url": "http://p3.theseed.org/services/shock_api",
            "keep_name": false,
            "local_file": "/scratch/tmp/7_Y5klbiK8/38-74_S95_L001_R2_001.fastq",
            "shock_id": "deddaed2-4cb5-4329-8d60-003d0af2dc15",
            "filename": "38-74_S95_L001_R2_001.fastq",
            "create_time": "2017-09-24 18:09:20.988685",
            "filesize": 170902577,
            "direct_url": null,
            "metadata": null
          }
        ],
        "type": "paired",
        "interleaved": "false"
      },
      {
        "tags": [

        ],
        "read_orientation_outward": "false",
        "platform": "infer",
        "file_infos": [
          {
            "shock_url": "http://p3.theseed.org/services/shock_api",
            "keep_name": false,
            "local_file": "/scratch/tmp/7_Y5klbiK8/38-74_S95_L001_R1_0011.fastq",
            "shock_id": "bf3edf19-2617-4f1c-a3e3-e87722d3b4cd",
            "filename": "38-74_S95_L001_R1_0011.fastq",
            "create_time": "2017-09-24 18:23:11.464102",
            "filesize": 128924081,
            "direct_url": null,
            "metadata": null
          },
          {
            "shock_url": "http://p3.theseed.org/services/shock_api",
            "keep_name": false,
            "local_file": "/scratch/tmp/7_Y5klbiK8/38-74_S95_L001_R2_0011.fastq",
            "shock_id": "ad1da4fb-0bb7-43fa-a47e-208015b7cb2b",
            "filename": "38-74_S95_L001_R2_0011.fastq",
            "create_time": "2017-09-24 18:35:19.619619",
            "filesize": 128678955,
            "direct_url": null,
            "metadata": null
          }
        ],
        "type": "paired",
        "interleaved": "false"
      }
    ]
  },
  "client": "CLI",
  "data_id": 248,
  "job_id": 248,
  "message": null,
  "oauth_token": "un=lkbryan@patricbrc.org|tokenid=be015d39-1ba7-4528-a2bc-5f5b0cccfb4a|expiry=1536536509|client_id=lkbryan@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=726ec328d9090203af308de70fd480b1be40289e849338db5c29b92677cea0ddd7a4e8aff0f4f72b1533a163798bcc4b380160866e8cbcc1a56191e2f8e387835a0c5b21cb573bc73051a80c4dc5fd05b53b2e0fe1dcca62ee42be583c34da78ccf36a7a7d6243127c3c7abcac83c8806c005ae7fd7014707eb70f4a74ca9448",
  "pipeline": null,
  "queue": null,
  "recipe": [
    "miseq"
  ],
  "status": "Queued",
  "version": "0.6.0",
  "wasp": null
}
```

**Comment by olsonanl** [comment]
This a job of the user's marked as running:

```
{
  "ARASTUSER": "lkbryan_patricbrc_org",
  "_id": ObjectId("59c954df64cc9007be243cfb"),
  "job_id": 166,
  "job_uid": "bd6b7c37-b9d6-4413-9923-36460b5f65a0",
  "pipeline": null,
  "status": "running",
  "timestamp": "1506367183.39"
}
```

I see this in the server log, with the rogue job status again.

```
[2017-09-24 04:27:06,684 INFO metadata] Job updated: bd6b7c37-b9d6-4413-9923-36460b5f65a0 - status - Queued
[2017-09-24 04:27:06,746 INFO pika.adapters.base_connection] Connecting to 140.221.78.14:5672
[2017-09-24 04:27:08,853 INFO router] Sent to queue: 'jobs.regular': '{"pipeline": null, "job_id": 166, "assembly_da
ta": {"file_sets": [{"tags": [], "read_orientation_outward": "false", "platform": "infer", "file_infos": [{"shock_ur
l": "http://p3.theseed.org/services/shock_api", "keep_name": false, "local_file": "/scratch/tmp/Ax5ti_Dg_4/11-25_S25
_L001_R1_001.fastq", "shock_id": "927dc115-2555-488f-9f3d-4deb499dff73", "filename": "11-25_S25_L001_R1_001.fastq", 
"create_time": "2017-09-24 09:00:30.093088", "filesize": 86364238, "direct_url": null, "metadata": null}, {"shock_ur
l": "http://p3.theseed.org/services/shock_api", "keep_name": false, "local_file": "/scratch/tmp/Ax5ti_Dg_4/11-25_S25
_L001_R2_001.fastq", "shock_id": "ffd57cdf-3f2b-44c9-81da-c229c8c8f1fc", "filename": "11-25_S25_L001_R2_001.fastq", 
"create_time": "2017-09-24 09:04:27.242073", "filesize": 64723186, "direct_url": null, "metadata": null}], "type": "
paired", "interleaved": "false"}, {"tags": [], "read_orientation_outward": "false", "platform": "infer", "file_infos
": [{"shock_url": "http://p3.theseed.org/services/shock_api", "keep_name": false, "local_file": "/scratch/tmp/Ax5ti_Dg_4/11-25_S25_L001_R1_0011.fastq", "shock_id": "9fb7474d-0ee7-4e2d-90f9-84b977b8c8fc", "filename": "11-25_S25_L001_R1_0011.fastq", "create_time": "2017-09-24 09:18:56.229632", "filesize": 148628179, "direct_url": null, "metadata": null}, {"shock_url": "http://p3.theseed.org/services/shock_api", "keep_name": false, "local_file": "/scratch/tmp/Ax5ti_Dg_4/11-25_S25_L001_R2_0011.fastq", "shock_id": "36645c93-9cb8-4907-91e1-85706e9483f1", "filename": "11-25_S25_L001_R2_0011.fastq", "create_time": "2017-09-24 09:27:00.351187", "filesize": 149255691, "direct_url": null, "metadata": null}], "type": "paired", "interleaved": "false"}]}, "data_id": 166, "ARASTUSER": "lkbryan_patricbrc_org", "wasp": null, "recipe": ["miseq"], "queue": null, "client": "CLI", "oauth_token": "un=lkbryan@patricbrc.org|tokenid=be015d39-1ba7-4528-a2bc-5f5b0cccfb4a|expiry=1536536509|client_id=lkbryan@patricbrc.org|token_type=Bearer|realm=patricbrc.org|SigningSubject=https://user.patricbrc.org/public_key|sig=726ec328d9090203af308de70fd480b1be40289e849338db5c29b92677cea0ddd7a4e8aff0f4f72b1533a163798bcc4b380160866e8cbcc1a56191e2f8e387835a0c5b21cb573bc73051a80c4dc5fd05b53b2e0fe1dcca62ee42be583c34da78ccf36a7a7d6243127c3c7abcac83c8806c005ae7fd7014707eb70f4a74ca9448", "version": "0.6.0", "message": null, "_id": "bd6b7c37-b9d6-4413-9923-36460b5f65a0"}'
```

**Comment by levinas** [comment]
Here's how Chris defined the rogue jobs:

> The Arast master keeps a "Running Jobs" list for the purpose of querying/killing/limiting per-user jobs.  Removing "rogue" jobs is just a periodic clean up of that list.  So any job that status isn't running/queued will be purged from the list.  This process shouldn't affect any logic that kills jobs.
>
> e.g. a job with status "[FAILED] ... " will be "rogue" and removed.  A job that has stopped giving time heartbeats will be marked as "stale" and removed from the list.

**Comment by olsonanl** [comment]
OK. Any ideas on what happened here then?

**Comment by olsonanl** [comment]
The job #166 that is listed as running failed out on a query:

```
olson@beech:/disks/p3/task_status$ tail ./53236d51-c2d6-46ad-82e6-9177bab96df2/stderr
2017-09-24 07:13:55: job 166 status: Queued
2017-09-24 07:24:43: job 166 status: Queued
2017-09-24 07:35:22: job 166 status: Queued
2017-09-24 07:45:38: job 166 status: Queued
2017-09-24 07:56:44: job 166 status: Queued
2017-09-24 08:07:15: job 166 status: Queued
2017-09-24 08:17:22: job 166 status: Queued
HTTP error: Internal Server Error (HTTP status code 500)

Error running status command ar-stat -j 166: No such file or directory at /disks/p3/deployment/plbin/App-GenomeAssembly.pl line 115.
```

Should we be ignoring failures like this on ar-stat? What is actually failing there?

**Comment by levinas** [comment]
I don't understand what happened there. Could it be the time when velvet was running elm out of memory? I do see multiple cherrypy.TimeoutError() around 2017-09-24 08:33. CherryPy is the web server and perhaps that's why the client got the 500 error.

**Comment by mshukla1** [comment]
@olsonanl is this still relevant or should I close it?

**Comment by olsonanl** [comment]
No, this is a weird arast thing so we can close.
