### ISSUE TITLE
Index worker keeps dying

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1738]
We have been having index worker croaks at least a couple times a day lately:

```
Error POSTing to : sp_gene - Error: socket hang up
Error POSTing documents to SOLR core :  sp_gene { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

resulting in a backlog of jobs in the annotation service.

**Comment by dmachi** [comment]
What is solr saying?  This seems like a proxy or solr server issue.  This code hasn't changed in over 2 years.

**Comment by olsonanl** [comment]
There are solr glitches that we are looking at, but the index worker needs to recover and get back to work without manual intervention.

**Comment by olsonanl** [comment]
This is what we are seeing in case you have any thoughts on it:

```
33619550 ERROR (qtp2076629294-181198) [   ] o.a.s.s.HttpSolrCall null:org.apache.solr.common.SolrException: Error handling 'status' action 
        at org.apache.solr.handler.admin.CoreAdminOperation$4.call(CoreAdminOperation.java:192)
        at org.apache.solr.handler.admin.CoreAdminHandler$CallInfo.call(CoreAdminHandler.java:354)
        at org.apache.solr.handler.admin.CoreAdminHandler.handleRequestBody(CoreAdminHandler.java:153)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
        at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:676)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:439)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:225)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:183)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /disks/space0/solr_indexes/patric_solr/genome_feature/data/index/segments_f97b
```

**Comment by olsonanl** [comment]
I'm going to move the solr issue to its own ticket to track details

**Comment by hyoo** [comment]
new indexer is deployed Dec 7 2017. I will keep watching it.

**Comment by hyoo** [comment]
new indexer have process more than 1k genomes over 5 days without failure. 

<img width="298" alt="image" src="https://user-images.githubusercontent.com/1236467/33895486-3bb66884-df26-11e7-893b-4b424065cfcb.png">

I haven't tested in situation where we index a couple of thousand genomes per day for data release preparation. I am going to close this and will watch in next data release.

**Comment by mshukla1** [comment]
Awesome! Thanks, Harry.
