### ISSUE TITLE
Solr errors on segment file missing

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1739]
We are seeing repeated failures in solr of the following form. Extended context included.

```
933986057 INFO  (qtp2076629294-181266) [   x:genome] o.a.s.u.p.LogUpdateProcessorFactory [genome]  webapp=/solr path=/update params={softCommit=true&wt=json}{commit=} 0 8
933986545 INFO  (qtp2076629294-181270) [   x:genome_amr] o.a.s.c.S.Request [genome_amr]  webapp=/solr path=/update params={commit=false&wt=json&overwrite=true} status=0 QTime=0
933986547 INFO  (qtp2076629294-181224) [   x:genome] o.a.s.u.p.LogUpdateProcessorFactory [genome]  webapp=/solr path=/update params={commit=false&wt=json&overwrite=true}{add=[562.19409 (1579887121083138048)]} 0 1
933986550 INFO  (qtp2076629294-181271) [   x:taxonomy] o.a.s.u.p.LogUpdateProcessorFactory [taxonomy]  webapp=/solr path=/update params={commit=false&wt=json&overwrite=true}{add=[131567 (1579887121085235200), 2 (1579887121086283776), 1224 (1579887121086283777), 1236 (1579887121087332352), 91347 (1579887121087332353), 543 (1579887121087332354), 561 (1579887121087332355), 562 (1579887121087332356)]} 0 2
933986745 INFO  (qtp2076629294-181245) [   x:genome_sequence] o.a.s.u.p.LogUpdateProcessorFactory [genome_sequence]  webapp=/solr path=/update params={commit=false&wt=json&overwrite=true}{add=[562.19409.con.0001 (1579887121086283776), 562.19409.con.0002 (1579887121087332352), 562.19409.con.0003 (1579887121087332353), 562.19409.con.0004 (1579887121087332354), 562.19409.con.0005 (1579887121087332355), 562.19409.con.0006 (1579887121088380928), 562.19409.con.0007 (1579887121088380929), 562.19409.con.0008 (1579887121088380930), 562.19409.con.0009 (1579887121088380931), 562.19409.con.0010 (1579887121088380932), ... (96 adds)]} 0 196
933986768 INFO  (commitScheduler-110-thread-1) [   x:sp_gene] o.a.s.u.DirectUpdateHandler2 start commit{,optimize=false,openSearcher=false,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
933986908 INFO  (qtp2076629294-181266) [   x:sp_gene] o.a.s.c.S.Request [sp_gene]  webapp=/solr path=/update params={commit=false&wt=json&overwrite=true} status=0 QTime=360
933986988 INFO  (qtp2076629294-181253) [   x:pathway] o.a.s.c.S.Request [pathway]  webapp=/solr path=/update params={commit=false&wt=json&overwrite=true} status=0 QTime=441
933987390 INFO  (commitScheduler-110-thread-1) [   x:sp_gene] o.a.s.c.SolrDeletionPolicy SolrDeletionPolicy.onCommit: commits: num=2
	commit{dir=NRTCachingDirectory(MMapDirectory@/disks/space0/solr_indexes/patric_solr/sp_gene/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@65c79a7; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_cm9j,generation=588727}
	commit{dir=NRTCachingDirectory(MMapDirectory@/disks/space0/solr_indexes/patric_solr/sp_gene/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@65c79a7; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_cm9k,generation=588728}
933987390 INFO  (commitScheduler-110-thread-1) [   x:sp_gene] o.a.s.c.SolrDeletionPolicy newest commit generation = 588728
933987490 INFO  (commitScheduler-110-thread-1) [   x:sp_gene] o.a.s.s.SolrIndexSearcher Opening Searcher@42dd49a8[sp_gene] realtime
933987494 INFO  (commitScheduler-110-thread-1) [   x:sp_gene] o.a.s.u.DirectUpdateHandler2 end_commit_flush
933987495 ERROR (qtp2076629294-181245) [   ] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Error handling 'status' action 
	at org.apache.solr.handler.admin.CoreAdminOperation$4.call(CoreAdminOperation.java:192)
	at org.apache.solr.handler.admin.CoreAdminHandler$CallInfo.call(CoreAdminHandler.java:354)
	at org.apache.solr.handler.admin.CoreAdminHandler.handleRequestBody(CoreAdminHandler.java:153)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
	at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:676)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:439)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:225)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:183)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /disks/space0/solr_indexes/patric_solr/sp_gene/data/index/segments_cm9j
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.size(Files.java:2332)
	at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:210)
	at org.apache.lucene.store.NRTCachingDirectory.fileLength(NRTCachingDirectory.java:127)
	at org.apache.solr.handler.admin.LukeRequestHandler.getIndexInfo(LukeRequestHandler.java:592)
	at org.apache.solr.handler.admin.CoreAdminOperation.getCoreStatus(CoreAdminOperation.java:886)
	at org.apache.solr.handler.admin.CoreAdminOperation$4.call(CoreAdminOperation.java:180)
	... 27 more

933987495 INFO  (qtp2076629294-181245) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={action=STATUS} status=500 QTime=29
933987495 ERROR (qtp2076629294-181245) [   ] o.a.s.s.HttpSolrCall null:org.apache.solr.common.SolrException: Error handling 'status' action 
	at org.apache.solr.handler.admin.CoreAdminOperation$4.call(CoreAdminOperation.java:192)
	at org.apache.solr.handler.admin.CoreAdminHandler$CallInfo.call(CoreAdminHandler.java:354)
	at org.apache.solr.handler.admin.CoreAdminHandler.handleRequestBody(CoreAdminHandler.java:153)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
	at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:676)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:439)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:225)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:183)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /disks/space0/solr_indexes/patric_solr/sp_gene/data/index/segments_cm9j
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.size(Files.java:2332)
	at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:210)
	at org.apache.lucene.store.NRTCachingDirectory.fileLength(NRTCachingDirectory.java:127)
	at org.apache.solr.handler.admin.LukeRequestHandler.getIndexInfo(LukeRequestHandler.java:592)
	at org.apache.solr.handler.admin.CoreAdminOperation.getCoreStatus(CoreAdminOperation.java:886)
	at org.apache.solr.handler.admin.CoreAdminOperation$4.call(CoreAdminOperation.java:180)
	... 27 more

933987902 INFO  (qtp2076629294-181270) [   x:genome_feature] o.a.s.u.p.LogUpdateProcessorFactory [genome_feature]  webapp=/solr path=/update params={commit=false&wt=json&overwrite=true}{add=[PATRIC.562.19409.FZIB01000096.CDS.3.239.fwd (1579887121087332352), PATRIC.562.19409.FZIB01000096.repeat_region.7.323.fwd (1579887121088380928), PATRIC.562.19409.FZIB01000093.repeat_region.1.123.fwd (1579887121088380929), PATRIC.562.19409.FZIB01000093.CDS.258.482.rev (1579887121088380930), PATRIC.562.19409.FZIB01000093.repeat_region.361.483.fwd (1579887121089429504), PATRIC.562.19409.FZIB01000089.CDS.3.449.fwd (1579887121089429505), PATRIC.562.19409.FZIB01000088.repeat_region.1.123.fwd (1579887121089429506), PATRIC.562.19409.FZIB01000088.tRNA.195.270.rev (1579887121089429507), PATRIC.562.19409.FZIB01000088.repeat_region.392.515.fwd (1579887121089429508), PATRIC.562.19409.FZIB01000086.repeat_region.8.131.fwd (1579887121090478080), ... (5397 adds)]} 0 1353
933987907 INFO  (qtp2076629294-181253) [   x:genome_feature] o.a.s.u.DirectUpdateHandler2 start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=true,prepareCommit=false}
933987907 INFO  (qtp2076629294-181245) [   x:pathway] o.a.s.u.DirectUpdateHandler2 start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=true,prepareCommit=false}
933987907 INFO  (qtp2076629294-181271) [   x:genome_amr] o.a.s.u.DirectUpdateHandler2 start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=true,prepareCommit=false}
933987907 INFO  (qtp2076629294-181255) [   x:genome_sequence] o.a.s.u.DirectUpdateHandler2 start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=true,prepareCommit=false}
933987907 INFO  (qtp2076629294-181224) [   x:sp_gene] o.a.s.u.DirectUpdateHandler2 start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=true,prepareCommit=false}
933987907 INFO  (qtp2076629294-181271) [   x:genome_amr] o.a.s.c.SolrCore SolrIndexSearcher has not changed - not re-opening: org.apache.solr.search.SolrIndexSearcher
933987907 INFO  (qtp2076629294-181270) [   x:taxonomy] o.a.s.u.DirectUpdateHandler2 start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=true,prepareCommit=false}
933987907 INFO  (qtp2076629294-181271) [   x:genome_amr] o.a.s.u.DirectUpdateHandler2 end_commit_flush
933987907 INFO  (qtp2076629294-181271) [   x:genome_amr] o.a.s.c.S.Request [genome_amr]  webapp=/solr path=/update params={softCommit=true&wt=json} status=0 QTime=0
933987908 INFO  (qtp2076629294-181224) [   x:sp_gene] o.a.s.s.SolrIndexSearcher Opening Searcher@6e5dce3e[sp_gene] main
933987909 INFO  (qtp2076629294-181224) [   x:sp_gene] o.a.s.u.DirectUpdateHandler2 end_commit_flush
933987909 INFO  (searcherExecutor-104-thread-1-processing-x:sp_gene) [   x:sp_gene] o.a.s.c.QuerySenderListener QuerySenderListener sending requests to Searcher@6e5dce3e[sp_gene] main{ExitableDirectoryReader(UninvertingDirectoryReader(Uninverting(_b5hx(5.5.0):C11827179/3783302:delGen=27449) Uninverting(_axky(5.5.0):C11675723/3666269:delGen=35781) Uninverting(_cjaj(5.5.0):C11647312/4431439:delGen=17880) Uninverting(_d5ix(5.5.0):C11638424/1395319:delGen=12151) Uninverting(_bxw6(5.5.0):C12047933/1265839:delGen=16282) Uninverting(_9p4l(5.5.0):C11375035/1582607:delGen=56212) Uninverting(_g31x(5.5.0):C11644870) Uninverting(_ctrl(5.5.0):C11866178/467176:delGen=14373) Uninverting(_dj3p(5.5.0):C11582003/282682:delGen=6104) Uninverting(_fhqb(5.5.0):c718677/1604:delGen=208) Uninverting(_g364(5.5.0):c228579) Uninverting(_g3se(5.5.0):c933509) Uninverting(_g4to(5.5.0):c959935) Uninverting(_g81o(5.5.0):c1194695) Uninverting(_g6xm(5.5.0):c866154) Uninverting(_g63k(5.5.0):c594643) Uninverting(_g7el(5.5.0):c68443) Uninverting(_g8ef(5.5.0):c140766) Uninverting(_g85k(5.5.0):c118763) Uninverting(_g82i(5.5.0):c6058) Uninverting(_g8bx(5.5.0):c5423) Uninverting(_g8c7(5.5.0):c38635) Uninverting(_g8ch(5.5.0):c6535) Uninverting(_g8ep(5.5.0):c15791) Uninverting(_g8f9(5.5.0):c19906) Uninverting(_g8ez(5.5.0):c18028) Uninverting(_g8ft(5.5.0):c18331) Uninverting(_g8eh(5.5.0):C4119) Uninverting(_g8eo(5.5.0):C2186) Uninverting(_g8fj(5.5.0):c18079) Uninverting(_g8f8(5.5.0):C2614) Uninverting(_g8fq(5.5.0):C2304) Uninverting(_g8fu(5.5.0):C1969) Uninverting(_g8fv(5.5.0):C1981) Uninverting(_g8fw(5.5.0):C2063) Uninverting(_g8fx(5.5.0):C1999) Uninverting(_g8fy(5.5.0):C1198) Uninverting(_g8fz(5.5.0):C777)))}
```

**Comment by olsonanl** [comment]
These errors are causing the nagios monitor to trip with error 500 responses to status calls, and with the indexing worker to fail (cf #1738)

**Comment by olsonanl** [comment]
Possibly related

https://github.com/yacy/yacy_search_server/commit/73ab4a7b3adf6ff1e10086199fa4324ecbc47da1

**Comment by olsonanl** [comment]
@danielolson5  does the nagios monitor retry the status check if it fails? And do we get any status text back with the 500 error?

I wonder if we are seeing transient errors that crop up during indexing because of out of sync references to index segments in solr. (The notes from the link I just posted appear to say this is a non-fatal error). 

This would inform the proper response of the index worker to these errors as well (to back off and retry request that get a 500).

**Comment by hyoo** [comment]
https://issues.apache.org/jira/browse/SOLR-8793?jql=text%20~%20%22java.nio.file.NoSuchFileException%20segment_%22

We're using 5.5.0 (https://github.com/PATRIC3/procedures/blob/master/solr-server-setup#L2)  and this issue fixed on 5.5.1

Since solr 7 is the newest version, we need to update our code base.

**Comment by olsonanl** [comment]
Will we need to update our plugins to do that?

**Comment by olsonanl** [comment]
BTW that bug report related to the status handler; we are also seeing problems with the index worker. However it does seem prudent to update the solr version.

**Comment by hyoo** [comment]
not plugin, this is a bug in solr 5.5.0. newer version should fix that. Actually I had worked on 5.5.1 and 5.5.3, but we didn't deploy with that. We can test and deploy 5.5.3 but, we are out-dated in major version and usually indexes are compatible only by one major version. So, we better to upgrade to 6.6 (lastest on 6) asap.

**Comment by olsonanl** [comment]
What is required to move forward with this?

**Comment by hyoo** [comment]
I need a day to checkout solr, apply custom data type, and see whether it works as we wanted and make a package so that you can deploy. don't know what will go wrong until i try, if that's the case, we can fall back to 5x and go with this version.

**Comment by olsonanl** [comment]
OK. There is a build package for p3 solr on spruce in /disks/patric-common/bootstrap/p3_solr that does a hands-off build from sources. We should get that updated for the latest version.

On Oct 2, 2017, at 11:37 AM, hyoo <notifications@github.com<mailto:notifications@github.com>> wrote:


I need a day to checkout solr, apply custom data type, and see whether it works as we wanted and make a package so that you can deploy. don't know what will go wrong until i try, if that's the case, we can fall back to 5x and go with this version.

**Comment by hyoo** [comment]
I cannot modify your file, but i tested on local. Please use this branch

https://github.com/PATRIC3/p3_solr/tree/lucene-solr_6.6.1_PATRIC

**Comment by olsonanl** [comment]
That builder is in github; I went ahead and did the tweaks needed to pull your new branch and it seems to have built fine. I'm now making a snapshot of the solr data from chestnut onto local disk on larch so we can try it out.

**Comment by hyoo** [comment]
I tested locally (with genome core) and it works as expected. you can deploy on chestnut after you feel comfortable.

**Comment by hyoo** [comment]
We have been running new solr for a couple of weeks and I don't see this issue anymore

![image](https://user-images.githubusercontent.com/1236467/31672125-4bd9f0fe-b321-11e7-8bd8-0079f5c015d2.png)

I am closing this issue. please reopen when this occur again
