### ISSUE TITLE
Keyword filter does not appear to be working in Transcriptomic genes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1771]
I have  uploaded one of the experiments that we use during the workshop, and filtered on Hypothetical.  No change in number.
<img width="744" alt="screen shot 2017-11-03 at 2 39 06 pm" src="https://user-images.githubusercontent.com/11475316/32390462-e869a280-c0a4-11e7-9627-811a1e5bc3dc.png">

The error code is below:
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:133:33)
    at Array.some (<anonymous>)
    at Object.eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:129:27)
    at Object.forEach (https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:62:384)
    at eval (/js/3.4.13/p3/layer/core.js:20:77)
    at https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:136:104
    at Array.h.(anonymous function) [as forEach] (/js/3.4.13/p3/layer/core.js:20:13)
    at Object.conditionFilter (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:80:9)
    at Object.eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:52:12)
    at e.<anonymous> (https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:58:501)
/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:133 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:133:33)
    at Array.some (<anonymous>)
    at Object.eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:129:27)
    at Object.forEach (https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:62:384)
    at eval (/js/3.4.13/p3/layer/core.js:20:77)
    at https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:136:104
    at Array.h.(anonymous function) [as forEach] (/js/3.4.13/p3/layer/core.js:20:13)
    at Object.conditionFilter (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:80:9)
    at Object.eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:52:12)
    at e.<anonymous> (https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:58:501)
/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:133 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:133:33)
    at Array.some (<anonymous>)
    at Object.eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:129:27)
    at Object.forEach (https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:62:384)
    at eval (/js/3.4.13/p3/layer/core.js:20:77)
    at https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:136:104
    at Array.h.(anonymous function) [as forEach] (/js/3.4.13/p3/layer/core.js:20:13)
    at Object.conditionFilter (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:80:9)
    at Object.eval (/js/3.4.13/p3/store/TranscriptomicsGeneMemoryStore.js:52:12)
    at e.<anonymous> (https://www.patricbrc.org/js/3.4.13/dojo/dojo.js:58:501)

**Comment by hyoo** [comment]
this is because refseq_locus_tag is empty. i will fix it soon.
