### ISSUE TITLE
Out of memory in Rockhopper

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1800]
Rockhopper job  a5ef59bf-5f1f-461d-a04e-12d131900b5c failed with heap memory error:

```
Sequencing reads written to SAM file:	/scratch/tmp/92KF8qRqhp/Rockhopper/Phage 13_R3.sam

Analyzing transcripts...

stderr:
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at Lowess.process(Lowess.java:175)
	at Lowess.lowess(Lowess.java:101)
	at Lowess.lowess(Lowess.java:33)
	at Gene.setLowessVariances(Gene.java:646)
	at Rockhopper.(Rockhopper.java:204)
	at Rockhopper.main(Rockhopper.java:908)
```

**Comment by mshukla1** [comment]
We removed RockHopper Recipe from the submission form, so I guess this is no longer an issue.
