### ISSUE TITLE
Invalid location crashes indexer

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1996]
If the indexer tries to index a feature with a non-numeric endpoint, it appears to crash, process no more features, and send no error message.

I see this in solr:

```
2018-05-21 17:46:25.259 ERROR (qtp1253382913-2390) [   x:genome_feature] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: ERROR: [doc=PATRIC.1231048
.6.NC_019918.CDS.<1.306.fwd] Error adding field 'start'='<1' msg=For input string: "<1"
        at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:240)
        at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:102)
        at org.apache.solr.update.DirectUpdateHandler2.updateDocument(DirectUpdateHandler2.java:922)
        at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:913)
        at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:302)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:194)
```

But nothing in the index worker error or output logs.

**Comment by hyoo** [comment]
thanks, i will include this for my test
