### ISSUE TITLE
Assembly submit failure

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2007]
Logging to check out and hopefully fix error logging. 

Job c47c0aba-53f2-44a4-bd9c-8d5499bc539e as reported in https://jira.cels.anl.gov/browse/PATRIC-1611

Problem appears to have been a shock upload failure in the arast client.

```
GET WS => /scratch/tmp/ASTqyyxqYC SRR4240359.fastq /PATRIC@patricbrc.org/PATRIC Workshop/ASM Microbe 
2018/Assembly/SRR4240359.fastq
\@submit_cmd = $VAR1 = [
          'ar-run',
          '-r',
          'auto',
          '--single',
          '/scratch/tmp/ASTqyyxqYC/SRR4240359.fastq',
          'platform=infer'
        ];
Running ar-run -r auto --single /scratch/tmp/ASTqyyxqYC/SRR4240359.fastq platform=infer
Error submitting run. Run command=ar-run -r auto --single /scratch/tmp/ASTqyyxqYC/SRR4240359.fastq pl
atform=infer, stdout:

stderr:
Traceback (most recent call last):
  File "/disks/p3/deployment/pybin/arast.py", line 410, in <module>
    main()
  File "/disks/p3/deployment/pybin/arast.py", line 388, in main
    run_command()
  File "/disks/p3/deployment/pybin/arast.py", line 375, in run_command
    cmd_run(args, aclient, usage, clientlog)
  File "/disks/p3/deployment/pybin/arast.py", line 167, in cmd_run
    data = prepare_assembly_data(args, aclient, usage)
  File "/disks/p3/deployment/pybin/arast.py", line 318, in prepare_assembly_data
    f_info = aclient.upload_data_file_info(word, curl=curl)
  File "/disks/p3/deployment/lib/assembly/client.py", line 53, in upload_data_file_info
    res = self.shock.upload_reads(filename, curl=curl)
  File "/disks/p3/deployment/lib/assembly/shock.py", line 124, in upload_reads
    return self.upload_file(filename, filetype='reads', curl=curl, auth=auth)
  File "/disks/p3/deployment/lib/assembly/shock.py", line 111, in upload_file
    res = self._post_file(filename, filetype, auth)
  File "/disks/p3/deployment/lib/assembly/shock.py", line 208, in _post_file
    res = json.loads(r.text)
  File "/disks/patric-common/runtime/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/disks/patric-common/runtime/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/disks/patric-common/runtime/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by dawenx** [comment]
bob, what do you plan to do with this issue?

**Comment by olsonanl** [comment]
Probably ignore since we're getting rid of arast.
Leave it open though.
