### ISSUE TITLE
Comprehensive Genome Analysis: Figure 3 is missing from the report

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#2298]
Figure 3 is missing from FullGenomeReport.html

![image](https://user-images.githubusercontent.com/6361802/61151889-97d29000-a4ac-11e9-9752-66faed99dcff.png)

**Comment by nconrad** [comment]
We think this was related to the Data API being down.  @chmao1 did you confirm this no longer an issue?

**Comment by chmao1** [comment]
This is still an issue. I reran the test after the DATA API came back last Friday and the figure 3 was still missing in the report.  
Please see:
https://beta.patricbrc.org/workspace/olson@patricbrc.org/PATRIC-QA/applications/App-ComprehensiveGenomeAnalysis/.Salmonella%20enterica%20test_SRR2/FullGenomeReport.html

**Comment by chmao1** [comment]
Job ID: 24272

Here is the error output:

Running process 18098 as task 1711
Executing under P3 shepherd 18095
Report headers from /olson@patricbrc.org/PATRIC-QA/applications/App-ComprehensiveGenomeAnalysis/.Salmonella enterica test_SRR2/.assembly/39_analysis.zip: Assembly	# contigs (>= 0 bp)	# contigs (>= 1000 bp)	Total length (>= 0 bp)	Total length (>= 1000 bp)	# contigs	Largest contig	Total length	GC (%)	N50	N75	L50	L75	# N's per 100 kbpSetting contigs to assembled contigs at /olson@patricbrc.org/PATRIC-QA/applications/App-ComprehensiveGenomeAnalysis/.Salmonella enterica test_SRR2/.assembly/contigs.fa
Writing to tempdir /disks/tmp/RG6aIhhsns
p3x-generate-circos generated truncation statistics: '90/90'
/disks/patric-common/runtime/lib/python2.7/site-packages/Bio/codonalign/__init__.py:585: UserWarning: fig|290338.8.peg.2689(M 0) does not correspond to fig|290338.8.peg.2689(gtg)
  % (pro.id, aa, aa_num, nucl.id, this_codon))
/disks/patric-common/runtime/lib/python2.7/site-packages/Bio/codonalign/__init__.py:585: UserWarning: fig|295319.15.peg.3006(M 0) does not correspond to fig|295319.15.peg.3006(ttg)
  % (pro.id, aa, aa_num, nucl.id, this_codon))
/disks/patric-common/runtime/lib/python2.7/site-packages/Bio/codonalign/__init__.py:585: UserWarning: fig|41514.7.peg.1(M 0) does not correspond to fig|41514.7.peg.1(gtg)
  % (pro.id, aa, aa_num, nucl.id, this_codon))
Jul 12, 2019 8:28:30 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Permission denied
Exception in thread "Thread-1" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
	at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
	at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
	at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)
Jul 12, 2019 8:28:34 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Permission denied
Exception in thread "Thread-1" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
	at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
	at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
	at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)
Jul 12, 2019 8:28:39 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Permission denied
Exception in thread "Thread-1" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
	at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
	at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
	at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)
Jul 12, 2019 8:28:44 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Permission denied
Exception in thread "Thread-1" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
	at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
	at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
	at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)
Jul 12, 2019 8:28:49 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Permission denied
Exception in thread "Thread-1" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
	at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
	at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
	at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)
Jul 12, 2019 8:28:55 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Permission denied
Exception in thread "Thread-1" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
	at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
	at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
	at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)
Codon tree codon_tree/CodonTree.nex does not exist at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/ComprehensiveGenomeAnalysis.pm line 562, <$fh> line 1.
	Bio::KBase::AppService::ComprehensiveGenomeAnalysis::compute_tree("annotation-with-stats.genome", "codon_tree", 10) called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/ComprehensiveGenomeAnalysis.pm line 426
	Bio::KBase::AppService::ComprehensiveGenomeAnalysis::generate_report(Bio::KBase::AppService::ComprehensiveGenomeAnalysis=HASH(0x26cde50)) called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/ComprehensiveGenomeAnalysis.pm line 107
	Bio::KBase::AppService::ComprehensiveGenomeAnalysis::run(Bio::KBase::AppService::ComprehensiveGenomeAnalysis=HASH(0x26cde50), Bio::KBase::AppService::AppScript=HASH(0x4528200), HASH(0x3477568), HASH(0x3477598), HASH(0x345def8)) called at /vol/patric3/production/P3Slurm/deployment/plbin/App-ComprehensiveGenomeAnalysis.pl line 16
	main::__ANON__(Bio::KBase::AppService::AppScript=HASH(0x4528200), HASH(0x3477568), HASH(0x3477598), HASH(0x345def8)) called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/AppScript.pm line 402
	eval {...} called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/AppScript.pm line 401
	Bio::KBase::AppService::AppScript::subproc_run(Bio::KBase::AppService::AppScript=HASH(0x4528200)) called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/AppScript.pm line 276
	Bio::KBase::AppService::AppScript::run(Bio::KBase::AppService::AppScript=HASH(0x4528200), ARRAY(0x26ce228)) called at /vol/patric3/production/P3Slurm/deployment/plbin/App-ComprehensiveGenomeAnalysis.pl line 18
Creating report with command: create-report -i annotation-with-stats.genome --n-contigs 90 --n-contigs-drawn 90 -o FullGenomeReport.html -c circos.svg -s subsystem_colors.json
*** Could not read tree view file: undefined
 TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:358:11)
    at internal/util.js:230:26
    at buildReport (/vol/patric3/production/P3Slurm/deployment/lib/genome_report/scripts/create-report.js:109:25)
    at 
$VAR1 = [
          [
            'Salmonella enterica test_SRR2',
            'job_result',
            '/olson@patricbrc.org/PATRIC-QA/applications/App-ComprehensiveGenomeAnalysis/',
            '2019-07-13T01:29:27Z',
            'A740EBCA-A50D-11E9-87A2-27A3682E0674',
            'cmao@patricbrc.org',
            19137,
            {},
            {
              'inspection_started' => '2019-07-13T01:29:27Z',
              'is_folder' => 0
            },
            'w',
            'n',
            ''
          ]
        ];

**Comment by ARWattam** [comment]
Shouldn’t the job ID be longer?  Like fe7ab36d-5777-44da-8e0e-4df2224ff939 (one of my recent job ids)?

**Comment by chmao1** [comment]
This job was run on PATRIC beta site. It seems that the job id on beta site uses different ID assign system. This one has job id 24272 instead of a long id.

Also, I noticed that on the job result page, it says job ID is 1711, which is task ID. This is confusing.

![image](https://user-images.githubusercontent.com/6361802/61464987-38113480-a945-11e9-80e6-60122223310d.png)

@olsonanl Bob, could you check this?

**Comment by chmao1** [comment]
Here is the display of the job ID on the job status page (Beta site)

![image](https://user-images.githubusercontent.com/6361802/61465368-f03edd00-a945-11e9-82fa-1aa8090fa638.png)

**Comment by ARWattam** [comment]
Thanks.  I sent to Bob.  We’ll see what he comes up with.

**Comment by olsonanl** [comment]
This was a permissions problem on the p3 home directory on one of the servers. I've restarted the job, new ID is 24283

**Comment by chmao1** [comment]
@olsonanl The job 24283 is complete. However, the figure 3 is still missing in the report. Here is the link to the report: https://beta.patricbrc.org/workspace/olson@patricbrc.org/PATRIC-QA/applications/App-ComprehensiveGenomeAnalysis/.Salmonella%20enterica%20test_SRR2/FullGenomeReport.html

Here is the error message:
Running process 23139 as task 1723
Executing under P3 shepherd 23136
Report headers from /olson@patricbrc.org/PATRIC-QA/applications/App-ComprehensiveGenomeAnalysis/.Salmonella enterica test_SRR2/.assembly/41_analysis.zip: Assembly	# contigs (>= 0 bp)	# contigs (>= 1000 bp)	Total length (>= 0 bp)	Total length (>= 1000 bp)	# contigs	Largest contig	Total length	GC (%)	N50	N75	L50	L75	# N's per 100 kbpSetting contigs to assembled contigs at /olson@patricbrc.org/PATRIC-QA/applications/App-ComprehensiveGenomeAnalysis/.Salmonella enterica test_SRR2/.assembly/contigs.fa
Writing to tempdir /disks/tmp/Soy03LRaVe
p3x-generate-circos generated truncation statistics: '90/90'
/disks/patric-common/runtime/lib/python2.7/site-packages/Bio/codonalign/__init__.py:585: UserWarning: fig|290338.8.peg.2689(M 0) does not correspond to fig|290338.8.peg.2689(gtg)
  % (pro.id, aa, aa_num, nucl.id, this_codon))
/disks/patric-common/runtime/lib/python2.7/site-packages/Bio/codonalign/__init__.py:585: UserWarning: fig|295319.15.peg.3006(M 0) does not correspond to fig|295319.15.peg.3006(ttg)
  % (pro.id, aa, aa_num, nucl.id, this_codon))
/disks/patric-common/runtime/lib/python2.7/site-packages/Bio/codonalign/__init__.py:585: UserWarning: fig|41514.7.peg.1(M 0) does not correspond to fig|41514.7.peg.1(gtg)
  % (pro.id, aa, aa_num, nucl.id, this_codon))
Codon tree codon_tree/CodonTree.nex does not exist at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/ComprehensiveGenomeAnalysis.pm line 562, <$fh> line 1.
	Bio::KBase::AppService::ComprehensiveGenomeAnalysis::compute_tree("annotation-with-stats.genome", "codon_tree", 10) called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/ComprehensiveGenomeAnalysis.pm line 426
	Bio::KBase::AppService::ComprehensiveGenomeAnalysis::generate_report(Bio::KBase::AppService::ComprehensiveGenomeAnalysis=HASH(0xdd5e50)) called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/ComprehensiveGenomeAnalysis.pm line 107
	Bio::KBase::AppService::ComprehensiveGenomeAnalysis::run(Bio::KBase::AppService::ComprehensiveGenomeAnalysis=HASH(0xdd5e50), Bio::KBase::AppService::AppScript=HASH(0x2c2ff78), HASH(0x1b7e250), HASH(0x1b7e280), HASH(0x1b63be0)) called at /vol/patric3/production/P3Slurm/deployment/plbin/App-ComprehensiveGenomeAnalysis.pl line 16
	main::__ANON__(Bio::KBase::AppService::AppScript=HASH(0x2c2ff78), HASH(0x1b7e250), HASH(0x1b7e280), HASH(0x1b63be0)) called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/AppScript.pm line 402
	eval {...} called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/AppScript.pm line 401
	Bio::KBase::AppService::AppScript::subproc_run(Bio::KBase::AppService::AppScript=HASH(0x2c2ff78)) called at /vol/patric3/production/P3Slurm/deployment/lib/Bio/KBase/AppService/AppScript.pm line 276
	Bio::KBase::AppService::AppScript::run(Bio::KBase::AppService::AppScript=HASH(0x2c2ff78), ARRAY(0xdd6228)) called at /vol/patric3/production/P3Slurm/deployment/plbin/App-ComprehensiveGenomeAnalysis.pl line 18
Creating report with command: create-report -i annotation-with-stats.genome --n-contigs 90 --n-contigs-drawn 90 -o FullGenomeReport.html -c circos.svg -s subsystem_colors.json
*** Could not read tree view file: undefined
 TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:358:11)
    at internal/util.js:230:26
    at buildReport (/vol/patric3/production/P3Slurm/deployment/lib/genome_report/scripts/create-report.js:109:25)
    at 
$VAR1 = [
          [
            'Salmonella enterica test_SRR2',
            'job_result',
            '/olson@patricbrc.org/PATRIC-QA/applications/App-ComprehensiveGenomeAnalysis/',
            '2019-07-18T22:28:11Z',
            '5323BE26-A9AB-11E9-84D8-9FF0682E0674',
            'cmao@patricbrc.org',
            19568,
            {},
            {
              'inspection_started' => '2019-07-18T22:28:11Z',
              'is_folder' => 0
            },
            'w',
            'n',
            ''
          ]
        ];
