### ISSUE TITLE
workspace ftp server crash

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2316]
The workspace node.js ftp server crashed with this error. Any ideas?

```
Error: Error Reading Stream from Workspace: /halilkurt@patricbrc.org/home/cmx/.R4-P2/.bin.4.1798454/load_files/genome_sequence.json
    at Error (native)
    at /homes/olson/P3/ftp/p3-ws-ftpd/wsReadStream.js:22:10
    at /homes/olson/P3/ftp/p3-ws-ftpd/workspaceFileSystem.js:380:6
    at notify (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:201:22)
    at notifyAll (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:180:5)
    at Promise.Deferred.reject.reject.errback.emitError (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:236:3)
    at notify (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:209:24)
    at notifyAll (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:180:5)
    at Promise.Deferred.resolve.callback.emitSuccess (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:223:3)
    at Request._callback (/homes/olson/P3/ftp/p3-ws-ftpd/workspaceFileSystem.js:50:8)
```

**Comment by dmachi** [comment]
Was there anything before this in the log? Like “STAT ERROR: ….”?

**Comment by olsonanl** [comment]
Yes:

```
Start Read for  /halilkurt@patricbrc.org/home/cmx/.R4-P2/.bin.5.2026780/bin.5.2026780.contigs.fasta
STAT:  /halilkurt@patricbrc.org/home/cmx/.R4-P2/.bin.5.2026780/bin.5.2026780.contigs.fasta
STAT ERROR:  Error: Object not found: 
    at /homes/olson/P3/ftp/p3-ws-ftpd/workspaceFileSystem.js:97:27
    at notify (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:201:22)
    at notifyAll (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:180:5)
    at Promise.Deferred.resolve.callback.emitSuccess (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:223:3)
    at Request._callback (/homes/olson/P3/ftp/p3-ws-ftpd/workspaceFileSystem.js:50:8)
    at Request.self.callback (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
STAT ERROR:  Error: Object not found: 
    at /homes/olson/P3/ftp/p3-ws-ftpd/workspaceFileSystem.js:97:27
    at notify (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:201:22)
    at notifyAll (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:180:5)
    at Promise.Deferred.resolve.callback.emitSuccess (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/promised-io/promise.js:223:3)
    at Request._callback (/homes/olson/P3/ftp/p3-ws-ftpd/workspaceFileSystem.js:50:8)
    at Request.self.callback (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/homes/olson/P3/ftp/p3-ws-ftpd/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
```

**Comment by dmachi** [comment]
Strange.  

The error happens when it cannot retrieve that file’s data meta object from the workspace api.  I su’d to that account and the file does exist, so its not clear to me why that part was happening in the first place.

Outside of that, it doesn’t seem like the ftpd server is capturing an error from that stat() operation it is calling.  I am throwing an error in this case,  but perhaps I’m not supposed to be.  I will investigate and see if I can figure out what it wants here.  It may be expecting the stream to emit an error rather than throwing an error as I currently do.
