### ISSUE TITLE
No checkboxes on feature list from transcriptomics experiment

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#700]
3.1.118alpha
Other tables have checkboxes.
![screen shot 2016-07-26 at 9 51 54 am](https://cloud.githubusercontent.com/assets/3188570/17142678/9ded5c3a-5316-11e6-8999-48021846b3bc.png)

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/TranscriptomicsGeneGrid.js#L21

When I  use custom store and turn on selector field, it breaks because it tries to access store before it gets created.

`instrumentation.js:20 TypeError: Cannot read property 'getIdentity' of null(…) "TypeError: Cannot read property 'getIdentity' of null
    at row (/js/dgrid/List.js:813:20)
    at Object.disabled (/js/p3/widget/GridSelector.js:19:34)
    at renderInput (/js/p3/widget/GridSelector.js:171:15)
    at Object.column.renderHeaderCell (/js/p3/widget/GridSelector.js:203:5)
    at eval (/js/dgrid/Grid.js:213:39)
    at createRowCells (/js/dgrid/Grid.js:144:6)
    at renderHeader (/js/dgrid/Grid.js:201:19)
    at inherited (/js/dojo/_base/declare.js:189:30)
    at renderHeader (/js/dgrid/extensions/ColumnReorder.js:158:9)
    at inherited (/js/dojo/_base/declare.js:189:30)"
`

One workaround is commenting these two line,
https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/GridSelector.js#L170-L171

Dustin, what do you think?

**Comment by mshukla1** [comment]
The same issue is present on protein family and pathway pages. 

-Maulik

**Comment by mshukla1** [comment]
#1218
