### ISSUE TITLE
Phylogeny tab blank

### ISSUE THREAD

**Issue by edietrich** [PATRIC3/patric3_website#762]
<img width="707" alt="screen shot 2016-07-26 at 10 47 20 am" src="https://cloud.githubusercontent.com/assets/8005288/17145028/62ec4d64-531e-11e6-9bde-e5ec95776af7.png">

**Comment by dmachi** [comment]
This generally works, but I think there is an error with strep that you are viewing here.  

```
typeError: Cannot read property '0' of undefined
    at getTipColors (/js/phyloview/TreeNavSVG.js:854:93)
    at setTree (/js/phyloview/TreeNavSVG.js:93:34)
    at processTree (/js/p3/widget/Phylogeny.js:99:14)
    at eval (/js/dojo/_base/lang.js:383:45)
    at notify (/js/dojo/Stateful.js:182:29)
    at callbacks._watchCallbacks (/js/dojo/Stateful.js:186:5)
    at _set (/js/dijit/_WidgetBase.js:877:11)
    at set (/js/dijit/_WidgetBase.js:841:10)
    at eval (/js/p3/widget/Phylogeny.js:79:10)
    at eval (/js/dojo/_base/lang.js:385:55)
    ----------------------------------------
```

**Comment by hyoo** [comment]
This works on beta. https://www.beta.patricbrc.org/view/Taxonomy/1301#view_tab=phylogeny

I am closing this ticket.
